### ISSUE TITLE
Spigot 1.12 Configuration issue

### ISSUE THREAD

**Issue by NicoDreamzZ** [greatman/GreatmancodeTools#4]
Hey there, i tried to use CraftConomy on Minecraft 1.12. It seems that Spigot removed some old apis. YamlConfiguration.loadConfiguration(InputStream) doesnt exists anymore. You use it in com.greatmancode.tools.configuration.bukkit.BukkitConfig. Please update this so CraftConomy works on Spigot 1.12.

**Comment by NicoDreamzZ** [comment]
` Error occurred while enabling Craftconomy3 v3.3-e72ac42-trv178 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
        at com.greatmancode.craftconomy3.tools.configuration.bukkit.BukkitConfig.<init>(BukkitConfig.java:59) ~[?:?]
        at com.greatmancode.craftconomy3.tools.interfaces.BukkitLoader.onEnable(BukkitLoader.java:43) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-ede465d-bb4ae3b]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
`

Maybe this error helps.

**Comment by NicoDreamzZ** [comment]
Ahh you already fixed it 8 minutes before my issue 👍 please close this issue
